[versions]
# kotlin
coroutines = "1.10.2"
kotlin = "2.1.20"
json = "1.8.1"
ktor = "3.1.3"

## Build
shadow = "9.0.0-beta13"

## PaperMC
paperweight = "2.0.0-beta.16"
runPaper = "2.3.1"

[libraries]
# Kotlin
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

ktor-content = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }

# Gradle
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

## PaperMC
paperweight = { module = "io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweight" }
runPaper = { module = "xyz.jpenilla:run-task", version.ref = "runPaper" }
[bundles]
build = [
    "kotlin"
]

ktor = [
    "ktor-content",
    "ktor-json",
    "ktor-core",
    "ktor-cio"
]