name: Test Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Notify Discord
        if: success()
        run: ./gradlew notify_snapshot --stacktrace
        env:
          BUILD_WEBHOOK: ${{ secrets.BUILD_WEBHOOK }}